@echo off
  curl -X POST "http://localhost:8000/api/events" \
  -H "Content-Type: multipart/form-data" \
  -F "title=React Mastery Conference" \
  -F "description=Learn React quickly with industry experts" \
  -F "category_id=ai-ml" \
  -F "start_date=2025-08-14" \
  -F "end_date=2025-08-14" \
  -F "start_time=09:00" \
  -F "end_time=15:00" \
  -F "venue_name=Kathmandu Center" \
  -F "location=Kathmandu" \
  -F "address=Kathmandu Center, Kathmandu" \
  -F "capacity=100" \
  -F "price=0" \
  -F "is_free=false" \
  -F "status=published" \
  -F "organizer_id=68be482c8e5fdffda60fea82" \
  -F "tags=[\"react\",\"javascript\",\"webdev\"]" \
  -F "tickets=[{\"name\":\"general\",\"price\":\"0\",\"capacity\":\"10\",\"description\":\"we\",\"sale_start_date\":\"2025-09-18\",\"sale_end_date\":\"2025-09-24\",\"is_free\":true}]" \
  -F "agenda=[{\"time\":\"09:00\",\"description\":\"Opening session\"},{\"time\":\"12:00\",\"description\":\"Main session\"}]" \
  -F "speakers=[{\"name\":\"Ramesh Gurung\",\"profession\":\"CEO React Tech\"}]" \
  -F "featured_image=@./test-image.jpg"